### ISSUE TITLE
Bugs: state was same on 9/30 and 10/1, and directions are not correct

### ISSUE THREAD

**Issue by jpozin** [eoncarlyle/state-economy-game#34]
![GDPLE 2024-09-30](https://github.com/user-attachments/assets/a2d85007-723c-4d85-abe4-9a594bc21ac2)
![GDPLE 2024-10-01](https://github.com/user-attachments/assets/5a14ea8b-ec1f-473b-80a9-1d5f4104c3b4)

The state of the day was Mississippi on 2024-09-30 and 2024-10-01. Furthermore, the direction between state centroids is incorrect (for example, in my first screenshot, Mississippi is not to the west of Hawaii)

**Comment by eoncarlyle** [comment]
Dear valued GDPLE player, thank you for this bug report! As the GDPLE backend has been overhauled, the timezone for the cronjob that rotates the puzzle answer was not property set to America/Chicago, longitudes had a sign error, and the Haversine bearing had one incorrect trigonometric function. The most recent [deployment](https://github.com/eoncarlyle/state-economy-game/actions/runs/11137158234/job/30950143442) should have addressed these issues, but we should be able to tell in the morning!

**Comment by eoncarlyle** [comment]
This should still be open, recent `StateEconomy` object changes broke the GDP calculation so the puzzle answer selection is still broken

```
Oct 01 23:55:22 new-york-0 dotnet[729319]:       Request finished HTTP/1.0 GET http://localhost:5000/health - 200 15 application/json;+charset=utf-8 0.1704ms
Oct 02 00:00:00 new-york-0 dotnet[729319]: Deleting System.Threading.Tasks.Task`1[System.Int32] obsolete sessions
Oct 02 00:00:00 new-york-0 dotnet[729319]: Deleting 1 obsolete puzzle answers
Oct 02 00:00:00 new-york-0 dotnet[729319]: Selected $REDACTED as the next puzzle answer
Oct 02 00:00:00 new-york-0 dotnet[729319]: fail: Quartz.Core.JobRunShell[0]
Oct 02 00:00:00 new-york-0 dotnet[729319]:       Job DEFAULT.runDailyTasks threw an unhandled Exception:
Oct 02 00:00:00 new-york-0 dotnet[729319]:       System.NullReferenceException: Object reference not set to an instance of an object.
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at Microsoft.FSharp.Collections.FSharpList`1.get_TailOrNull()
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at StateEconomyGame.Service.loop@55.Invoke(EconomyNode economyNode) in /home/iain/f-sharp-backend/Service.fs:line 55
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in /builddir/build/BUILD/dotnet-8.0.8/src/f>
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in /builddir/build/BUILD/dotnet-8.0.8/sr>
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at StateEconomyGame.Service.loop@55.Invoke(EconomyNode economyNode) in /home/iain/f-sharp-backend/Service.fs:line 57
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in /builddir/build/BUILD/dotnet-8.0.8/src/f>
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in /builddir/build/BUILD/dotnet-8.0.8/sr>
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at StateEconomyGame.Service.loop@55.Invoke(EconomyNode economyNode) in /home/iain/f-sharp-backend/Service.fs:line 57
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at StateEconomyGame.Service.getTotalGdp(State economyNode) in /home/iain/f-sharp-backend/Service.fs:line 59
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at StateEconomyGame.Service.updatePuzzleAnswer@319.MoveNext() in /home/iain/f-sharp-backend/Service.fs:line 339
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at StateEconomyGame.Service.Quartz-IJob-Execute@359.MoveNext() in /home/iain/f-sharp-backend/Service.fs:line 366
Oct 02 00:00:00 new-york-0 dotnet[729319]:          at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
```

**Comment by eoncarlyle** [comment]
Commit 4cb23a29a6ffb9d912769aaf73c619a8a3d8d363 applied the fix
